In [2]:
class Employee: #Employee Class
    empCount=0 #empCount is used to keep track of number of employee objects
    salSum=0 #salSum is used for average of salaries of the employee objects
    def __init__(self,name,family,salary,department): #constructor for employee as per given requirements
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.empCount+=1
        Employee.salSum+=self.salary
    def avg(self): #function
        return Employee.salSum/Employee.empCount
    def displayCount(self): #function
        print("Total Employee %d" %Employee.empCount)
    def displayEmployee(self): #function
        print("Name: ",self.name,  "Family: ",self.family ,  "Salary: ",self.salary ,  "department: ",self.department)
emp1 = Employee("Akhil", "Aliza", 4000, "software") # employee object creation
emp2 = Employee("Kartheek", "Kumar", 5000, "Electrical")
print("avg:", emp2.avg()) #calling average function

class FulltimeEmployee(Employee): #FulltimeEmployee class
    def __init__(self,name,family,salary,department,c_name): #constructor for FulltimeEmployee
        super().__init__(name,family,salary,department)
        self.c_name=c_name
    def setCompany(self,c_name): #function
        self.c_name=c_name
    def getCompany(self): #function
        if self.c_name not in self.c_name:
            return ""
        return self.c_name
f_emp = FulltimeEmployee("Harika", "Aliza", 20000, "Devops Engineer", "Amazon") #FulltimeEmployee object creation
f_emp.setCompany("Meta") #calling the member functions of FulltimeEmployee and Employee
f_emp.getCompany(),f_emp.displayEmployee(),emp1.displayCount()

avg: 4500.0
Name:  Harika Family:  Aliza Salary:  20000 department:  Devops Engineer
Total Employee 3


('Meta', None, None)

In [3]:
import numpy as np

# Create a random vector of size 20 with float values in the range 1-20
random_vector = np.random.uniform(1, 15, 20)

# Reshape the array to 4 by 5
reshaped_array = random_vector.reshape(4,5)

# Replace the max in each row by 0(axis=1)
reshaped_array[np.arange(4), np.argmax(reshaped_array, axis=1)] = 0

print("Random Vector:")
print(random_vector)

print("\nReshaped Array:")
print(reshaped_array)

Random Vector:
[ 7.69780207  5.66074058  4.54008606  0.          3.30284232  7.60930365
  3.51307799  7.16379338  0.         11.22340668  0.          3.64837311
  6.81821779 10.89857315 12.28936343  6.67265054  7.29035235  0.
  5.27976064  9.05720116]

Reshaped Array:
[[ 7.69780207  5.66074058  4.54008606  0.          3.30284232]
 [ 7.60930365  3.51307799  7.16379338  0.         11.22340668]
 [ 0.          3.64837311  6.81821779 10.89857315 12.28936343]
 [ 6.67265054  7.29035235  0.          5.27976064  9.05720116]]
